import { StudyItem } from './types';

const generateId = () => Math.random().toString(36).substr(2, 9);

export const DEFAULT_STUDY_DATA: StudyItem[] = [
  // --- 8AU1 Phrases ---
  { id: generateId(), group: "8AU1", english: "look up", chinese: "查询，查找", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU1", english: "an encyclopedia entry", chinese: "一个百科全书条目", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU1", english: "look through", chinese: "浏览", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU1", english: "die out / down", chinese: "灭绝；减弱", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU1", english: "be ... talented in / show ... talent", chinese: "在...方面有...天赋/ 展现...才华", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU1", english: "be born in", chinese: "在...出生", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU1", english: "from an early age", chinese: "从很小的时候", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU1", english: "as sb. grew older", chinese: "随着某人年龄的增长", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU1", english: "a type/kind of", chinese: "一种", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU1", english: "be related to", chinese: "与...属于同一种类", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU1", english: "come from", chinese: "来自", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU1", english: "either...or / neither...nor", chinese: "不是...就是/既不...也不", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU1", english: "as + adj./adv. + as...", chinese: "像...一样...", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU1", english: "more than / less than", chinese: "超过/少于", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU1", english: "be (not) sure", chinese: "确信/不确信", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU1", english: "connection between A and B", chinese: "A 与 B 之间的联系", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU1", english: "in one way", chinese: "在某种程度上", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU1", english: "national anthem", chinese: "国歌", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU1", english: "original name / nickname", chinese: "原名/ 绰号，昵称", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU1", english: "a dinosaur expert", chinese: "一位恐龙专家", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU1", english: "agree/disagree about", chinese: "对...意见统一/意见不统一", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU1", english: "the development of modern art", chinese: "现代艺术发展", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU1", english: "basic information", chinese: "基本信息", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU1", english: "main achievements", chinese: "主要成就", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU1", english: "awards and titles", chinese: "奖项和头衔", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU1", english: "all kinds of", chinese: "各种各样的", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU1", english: "general education", chinese: "通识教育", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU1", english: "be written by", chinese: "作者是", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU1", english: "be similar to", chinese: "与...相似", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU1", english: "play an important role in", chinese: "在…中起重要作用", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },

  // --- 8AU1 Sentences ---
  { id: generateId(), group: "8AU1", english: "Da Vinci was extremely intelligent, and he was unusually talented in many different fields.", chinese: "达芬奇非常聪明，他在许多不同的领域都有非凡的才能。", type: 'sentence', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU1", english: "As he grew older, he learnt to do many different things.", chinese: "随着年龄的增长，他学会了做许多不同的事情。", type: 'sentence', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU1", english: "Dinosaurs lived on land and walked on either two or four legs.", chinese: "恐龙生活在陆地上，用两条腿或四条腿走路。", type: 'sentence', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU1", english: "Yuan’s work has helped feed people in China and many other parts of the world.", chinese: "袁隆平的工作帮助养活了中国和世界许多地方的人们。", type: 'sentence', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU1", english: "Encyclopaedias have played an important role through history in recording and providing information.", chinese: "百科全书在历史中起到了重要作用，记录和提供信息。", type: 'sentence', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },

  // --- 8AU2 Phrases ---
  { id: generateId(), group: "8AU2", english: "flight schedule", chinese: "航班时刻表", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU2", english: "a wise man", chinese: "一位智者", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU2", english: "challenge sb. to sth.", chinese: "挑战某人做某事", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU2", english: "think for a moment", chinese: "思考了一会儿", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU2", english: "one grain of rice", chinese: "一粒米", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU2", english: "the square of the chessboard", chinese: "棋盘的格", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU2", english: "double the amount", chinese: "数量翻倍", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU2", english: "the rest of", chinese: "......的剩余部分", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU2", english: "without hesitation", chinese: "毫不犹豫", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU2", english: "order sb. to do sth.", chinese: "命令某人做某事", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU2", english: "and so on", chinese: "等等", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU2", english: "realize the problem", chinese: "意识到问题", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU2", english: "promise to do", chinese: "承诺做......", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU2", english: "ask sb. for advice", chinese: "向某人寻求建议", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU2", english: "take/follow one’s advice", chinese: "采纳某人的建议", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU2", english: "make a profit/budget", chinese: "获利/做预算", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU2", english: "in time", chinese: "及时；不久；将来", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU2", english: "record and present information", chinese: "记录并呈现信息", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU2", english: "take...for example", chinese: "以...为例", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU2", english: "be based on", chinese: "基于", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU2", english: "a line graph", chinese: "折线图", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU2", english: "rise/fall sharply", chinese: "急剧上升/下降", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU2", english: "go up/down", chinese: "上升/下降", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU2", english: "stay/remain the same", chinese: "保持不变", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU2", english: "replace A with B", chinese: "用 B 替换 A", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU2", english: "stand for", chinese: "代表", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU2", english: "write down", chinese: "写下", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU2", english: "instead of (doing) sth.", chinese: "代替，而不是", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU2", english: "spread to", chinese: "传播到", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU2", english: "be known as", chinese: "被称为......", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },

  // --- 8AU2 Sentences ---
  { id: generateId(), group: "8AU2", english: "One day, a wise old man came to the palace and the king challenged him to a game.", chinese: "一天，一位充满智慧的长者来到王宫，国王向他发起了挑战。", type: 'sentence', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU2", english: "I’d like you to double the amount for each of the rest of the squares.", chinese: "我想要你在剩余的每个格里依次增加一倍大米的数量。", type: 'sentence', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU2", english: "The graph shows that Shenzhen experienced great population changes from 1979 to 2024.", chinese: "这张图表表明深圳在 1979 到 2024 年间经历了巨大的人口变化。", type: 'sentence', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU2", english: "In ancient times, people developed different counting methods.", chinese: "在古代，人们发展出了不同的计数方法。", type: 'sentence', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU2", english: "The Roman numerals used to be the most common way of writing numbers in Europe.", chinese: "罗马数字曾经是欧洲最常用的数字书写方式。", type: 'sentence', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },

  // --- 8AU3 Phrases ---
  { id: generateId(), group: "8AU3", english: "special features", chinese: "特色；特点；特征", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU3", english: "wake up", chinese: "醒；醒来", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU3", english: "come back from", chinese: "从……回来", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU3", english: "start/begin to do sth./start doing sth.", chinese: "开始做某事", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU3", english: "work one’s land", chinese: "耕种土地", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU3", english: "It is exciting to do sth.", chinese: "做某事令人兴奋", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU3", english: "take a trip in the countryside", chinese: "去乡村旅行", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU3", english: "in the clear, blue sky", chinese: "在晴朗、湛蓝的天空中", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU3", english: "be full of ...", chinese: "充满……", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU3", english: "gather food for the cold winter", chinese: "为寒冷的冬天收集食物", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU3", english: "be busy with", chinese: "忙于", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU3", english: "go on a family outing", chinese: "全家一起远足", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU3", english: "at this time of year", chinese: "在一年中的这个时候", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU3", english: "through the winter", chinese: "整个冬天", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU3", english: "play in the snow", chinese: "在雪地里玩耍", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU3", english: "the 24 solar terms", chinese: "二十四节气", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU3", english: "the traditional Chinese calendar", chinese: "农历", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU3", english: "in fact", chinese: "事实上", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU3", english: "be divided into", chinese: "被划分成……", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU3", english: "be based on", chinese: "基于……", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU3", english: "start with", chinese: "以……开始", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU3", english: "Start of Spring", chinese: "立春", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU3", english: "fall on", chinese: "发生", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU3", english: "in daily life", chinese: "在日常生活中", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU3", english: "for example / such as", chinese: "例如", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU3", english: "plant crops", chinese: "种植庄稼", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU3", english: "play an important part in", chinese: "在……上发挥重要作用", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU3", english: "traditional Chinese culture", chinese: "中国传统文化", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU3", english: "spring rolls", chinese: "春卷", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU3", english: "spring pancakes", chinese: "春饼", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },

  // --- 8AU3 Sentences ---
  { id: generateId(), group: "8AU3", english: "In autumn, leaves turn brown, red or yellow and start falling down from the trees.", chinese: "秋天叶子变成了棕色、红色、黄色，开始从树上飘落下来。", type: 'sentence', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU3", english: "It is exciting to take a trip in the countryside in springtime.", chinese: "在春天，去乡村旅行是令人兴奋的。", type: 'sentence', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU3", english: "In fact, the year is divided into 24 parts, based on where the sun is in the sky.", chinese: "实际上，一年被分为 24 个部分，是根据太阳在天空中的位置来划分的。", type: 'sentence', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU3", english: "Each of the seasons is then divided into six parts, and each part lasts about 15 days.", chinese: "每个季节又被分为六个部分，每个部分持续约 15 天。", type: 'sentence', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU3", english: "People celebrated these days in different ways such as eating special local dishes.", chinese: "人们以不同的方式庆祝这些日子，比如吃当地的特色菜肴。", type: 'sentence', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },

  // --- 8AU4 Phrases ---
  { id: generateId(), group: "8AU4", english: "70% of the Earth (%: percent)", chinese: "地球的 70%", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU4", english: "be covered by water", chinese: "被水所覆盖", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU4", english: "protect the Earth", chinese: "保护地球", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU4", english: "on Earth", chinese: "在地球上", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU4", english: "on the land", chinese: "在陆地上", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU4", english: "in the sky", chinese: "在空中", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU4", english: "under the water/under the ground", chinese: "在水下/在地下", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU4", english: "people like you and me", chinese: "如你我之人；芸芸众生", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU4", english: "provide sb. with sth./ provide sth. for sb.", chinese: "为某人提供某物", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU4", english: "make energy", chinese: "获取能源，获得能量", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU4", english: "put …into…", chinese: "把…倒入；把…放进", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU4", english: "stop doing sth", chinese: "停止做某事；别再做某事", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU4", english: "It’s important for sb. to do sth.", chinese: "做某事对某人很重要", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU4", english: "for our future", chinese: "为了我们的未来", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU4", english: "set…on fire", chinese: "烧；把…置于火上", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU4", english: "keep …safe", chinese: "保护；使…安全", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU4", english: "for example", chinese: "比如；例如；举例说明", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU4", english: "one quarter/three quarters", chinese: "四分之一/四分之三", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU4", english: "a world map/a map of the world", chinese: "一幅世界地图", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU4", english: "throw…into…", chinese: "把…扔进", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU4", english: "throw away", chinese: "扔掉", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU4", english: "take a photo", chinese: "拍一张照片", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU4", english: "on the beach", chinese: "在沙滩上", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU4", english: "take a look at…/have a look at…=look at…", chinese: "看一看…; 看一下…", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU4", english: "ask sb. for sth.", chinese: "向…要…", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU4", english: "turn into", chinese: "变成", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU4", english: "blow away", chinese: "吹走", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU4", english: "keep…alive", chinese: "存活；使…活着", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU4", english: "a long time ago", chinese: "很久以前", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU4", english: "in the end", chinese: "最终；终于", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },

  // --- 8AU4 Sentences ---
  { id: generateId(), group: "8AU4", english: "The Earth provides us with all the things we need, such as food, water, air and energy.", chinese: "地球为我们提供了所有我们需要的东西，比如食物，水 空气和能量。", type: 'sentence', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU4", english: "The Earth is home to millions of animals.", chinese: "地球是数百万动物的家园。", type: 'sentence', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU4", english: "Three generations of forest workers continued the hard work.", chinese: "三代护林人持续着这项艰辛的工作。", type: 'sentence', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU4", english: "We must stop doing these things.", chinese: "我们必须停止做这些事。", type: 'sentence', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU4", english: "It is important for us to protect the Earth for our future.", chinese: "为了我们的未来，保护地球对我们很重要。", type: 'sentence', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },

  // --- 8AU5 Phrases ---
  { id: generateId(), group: "8AU5", english: "at the weekend/at weekends", chinese: "在周末/在每个周末", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU5", english: "go on tours with...", chinese: "和……去游览", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU5", english: "visit places of interest", chinese: "参观名胜古迹", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU5", english: "such as /for example /for instance", chinese: "比如", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU5", english: "in person", chinese: "亲自", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU5", english: "snake its way through", chinese: "蜿蜒穿过", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU5", english: "get to do sth.", chinese: "有机会做某事", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU5", english: "so far", chinese: "到目前为止", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU5", english: "a bit of+n. / a bit+adj./adv.", chinese: "一点....../有点......", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU5", english: "introduce sb to sth.", chinese: "使某人了解某物", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU5", english: "as well", chinese: "也", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU5", english: "be different from……", chinese: "与……不同", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU5", english: "keep trying", chinese: "继续尝试", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU5", english: "plan to do sth.", chinese: "计划做某事", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU5", english: "keep in touch with sb", chinese: "与某人保持联系", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU5", english: "one another", chinese: "互相，彼此", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU5", english: "come over to", chinese: "来到", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU5", english: "can’t wait (to do sth.)", chinese: "迫不及待（做......）", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU5", english: "be grateful for……", chinese: "对……心存感激", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU5", english: "culture shock", chinese: "文化冲击", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU5", english: "feel unhappy about life", chinese: "对生活感到不满", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU5", english: "find it difficult to do sth.", chinese: "发现做某事很难", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU5", english: "deal with", chinese: "处理；应对", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU5", english: "in most situations", chinese: "在大多数情况下", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU5", english: "no longer/not...any more", chinese: "不再……", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU5", english: "feel at home", chinese: "感到舒适自在", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU5", english: "adapt to change", chinese: "适应变化", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU5", english: "depend on", chinese: "取决于", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU5", english: "see things from different points of view", chinese: "从不同的角度看待事物", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU5", english: "get along (well) with sb", chinese: "与……相处（得好）", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },

  // --- 8AU5 Sentences ---
  { id: generateId(), group: "8AU5", english: "At the weekend, they go on tours with their host families around Beijing and visit places of interest, such as the Great Wall, the Summer Palace and the National Museum.", chinese: "在周末，他们与寄宿家庭一起游览北京，参观名胜古迹，例如长城、颐和园和国家博物馆。", type: 'sentence', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU5", english: "The Great Wall is no doubt one of the most amazing achievements in human history!", chinese: "长城无疑是人类历史上最惊人的成就之一！", type: 'sentence', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU5", english: "The students also spend time learning about Chinese culture.", chinese: "学生们还花时间了解中国文化。", type: 'sentence', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU5", english: "It's been a fantastic experience so far.", chinese: "到目前为止，这是一次极好的经历。", type: 'sentence', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU5", english: "If you travel to a foreign country, you may feel confused, strange or anxious.", chinese: "如果你去国外旅行，你可能会感到困惑、陌生或焦虑。", type: 'sentence', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },

  // --- 8AU6 Phrases ---
  { id: generateId(), group: "8AU6", english: "common features", chinese: "共同特点", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU6", english: "take place", chinese: "发生", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU6", english: "at a time", chinese: "一次", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU6", english: "look down at", chinese: "向下看，俯视", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU6", english: "sail away", chinese: "扬帆远去", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU6", english: "take sth. with sb.", chinese: "某人带上......", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU6", english: "pull sth. into sp.", chinese: "把......拉到......", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU6", english: "on wheels", chinese: "带轮子的", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU6", english: "obey order", chinese: "服从命令", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU6", english: "celebrate one’s victory", chinese: "庆祝某人的胜利", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU6", english: "make jokes about...", chinese: "开......的玩笑", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU6", english: "by midnight", chinese: "到午夜时分时", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU6", english: "except for", chinese: "除了", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU6", english: "make one’s way to", chinese: "前往......", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU6", english: "take over", chinese: "占领", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU6", english: "in the end", chinese: "最后", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU6", english: "succeed in doing sth.", chinese: "成功做......", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU6", english: "be located in", chinese: "位于......", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU6", english: "be tired of", chinese: "厌烦......", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU6", english: "go on board", chinese: "上船，登机", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU6", english: "pretend to do sth.", chinese: "假装做......", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU6", english: "be jealous of", chinese: "嫉妒......", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU6", english: "on the other side of", chinese: "在......另一边", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU6", english: "under attack", chinese: "遭受攻击", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU6", english: "be full of/be filled with", chinese: "充满", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU6", english: "turn...around", chinese: "掉头", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU6", english: "be able to do sth.", chinese: "有能力做某事", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU6", english: "order sb. to do sth.", chinese: "命令某人做某事", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU6", english: "within ten days", chinese: "十天内", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU6", english: "figure out", chinese: "弄明白，解决", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },

  // --- 8AU6 Sentences ---
  { id: generateId(), group: "8AU6", english: "The Greek army has tried for ten years to capture our city.", chinese: "希腊军队十年来一直试图占领我们的城市。", type: 'sentence', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU6", english: "Outside the main gate of the city stood a huge wooden horse.", chinese: "一座巨大的木马矗立在这座城市的主城门之外(倒装句，强调木马所在位置)。", type: 'sentence', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU6", english: "In the end, they succeeded in capturing it in just one night with a clever trick.", chinese: "最终，他们用一个巧妙的计谋，仅仅一个晚上就成功拿下了这座城。", type: 'sentence', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU6", english: "Zhou Yu was jealous of Zhuge Liang and wanted him to fail.", chinese: "周瑜嫉妒诸葛亮，想让他出丑(想让他失败)。", type: 'sentence', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU6", english: "The soldiers shouted and beat their drums loudly.", chinese: "士兵们大声呼喊，用力击鼓。", type: 'sentence', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },

  // --- 8AU7 Phrases ---
  { id: generateId(), group: "8AU7", english: "play an important role in", chinese: "在……中扮演重要角色", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU7", english: "plan to do sth.", chinese: "计划做某事", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU7", english: "take notes", chinese: "做笔记", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU7", english: "in one's mind", chinese: "在某人脑海中", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU7", english: "make a point of doing sth.", chinese: "(因重要或必要)保证做", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU7", english: "in the future", chinese: "在将来", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU7", english: "make up a story", chinese: "编一个故事", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU7", english: "so that", chinese: "为了；以便", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU7", english: "as well as", chinese: "和；以及；还有", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU7", english: "live a healthy life", chinese: "过健康的生活", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU7", english: "What's more", chinese: "此外；更重要的是", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU7", english: "regular physical exercise", chinese: "规律的锻炼", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU7", english: "a healthy diet", chinese: "健康的饮食", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU7", english: "maintain a good memory", chinese: "保持良好的记忆力", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU7", english: "Last but not least", chinese: "最后但同样重要的是", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU7", english: "plenty of", chinese: "大量", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU7", english: "experience memory loss", chinese: "经历记忆力衰退", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU7", english: "no wonder", chinese: "难怪", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU7", english: "take … out of​", chinese: "把……从……中拿出来", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU7", english: "take time to relax", chinese: "花时间放松", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU7", english: "tend to do sth.", chinese: "倾向于做某事", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU7", english: "a summary of", chinese: "……的总结", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU7", english: "as a result", chinese: "结果", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU7", english: "figure out", chinese: "弄懂；弄清楚", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU7", english: "be made up of", chinese: "由……组成", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU7", english: "seem like", chinese: "似乎是", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU7", english: "even though", chinese: "尽管", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU7", english: "a record of", chinese: "……的记录", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU7", english: "natural disasters", chinese: "自然灾害", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU7", english: "It’s amazing that +句子", chinese: "令人惊奇的是……", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },

  // --- 8AU7 Sentences ---
  { id: generateId(), group: "8AU7", english: "You will be exercising your brain as well as improving your memory!", chinese: "这样既锻炼了大脑，又提升了记忆力！", type: 'sentence', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU7", english: "Unless you take time to relax, your brain will find it hard to remember things.", chinese: "除非花时间放松，否则大脑会难以记住信息。", type: 'sentence', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU7", english: "What’s more, regular physical exercise and getting enough sleep also help improve your memory.", chinese: "此外，规律的锻炼和充足的睡眠也能帮助改善记忆。", type: 'sentence', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU7", english: "Therefore, it is quite normal for people to experience memory loss as they get older.", chinese: "因此，人们随着年龄增长出现记忆力减退是正常现象。", type: 'sentence', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU7", english: "This is a good sign as it means the tree grew well and was healthy.", chinese: "这是一个好迹象，因为这表明树木生长良好且健康。", type: 'sentence', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },

  // --- 8AU8 Phrases ---
  { id: generateId(), group: "8AU8", english: "grow up", chinese: "长大；成熟", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU8", english: "have to do sth.", chinese: "不得不做......", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU8", english: "according to......", chinese: "根据......", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU8", english: "care for = look after = take care of", chinese: "照顾；照料", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU8", english: "be pleased to do sth.", chinese: "很高兴做某事", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU8", english: "in short", chinese: "总之；简言之", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU8", english: "need to do sth.", chinese: "需要做某事", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU8", english: "keep sb. awake", chinese: "使某人保持清醒", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU8", english: "a small number of+n.复数", chinese: "少数的……", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU8", english: "what’s more = in addition", chinese: "此外；除......以外", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU8", english: "have no choice but to do sth.", chinese: "别无选择，只能……", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU8", english: "most of the time", chinese: "大多数时候", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU8", english: "run free", chinese: "自由奔跑", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU8", english: "because of +n./pron.", chinese: "因为；由于......", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU8", english: "advise sb. ( not ) to do sth.", chinese: "建议某人（不要）做某事", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU8", english: "lie around", chinese: "懒散度日；游手好闲", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU8", english: "take up much space", chinese: "占用很多空间", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU8", english: "on one's own", chinese: "独自地；独立地", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU8", english: "add up", chinese: "合计", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU8", english: "on the whole", chinese: "总之；总体而言", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU8", english: "complain about......", chinese: "抱怨......", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU8", english: "the other day", chinese: "前几天", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU8", english: "in one's opinion", chinese: "在某人看来", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU8", english: "find out", chinese: "发现；查明；弄清楚", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU8", english: "bring good luck", chinese: "带来好运", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU8", english: "a symbol of", chinese: "……的象征", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU8", english: "all kinds of", chinese: "各种各样的", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU8", english: "catch the eye of sb.", chinese: "引起某人的注意", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU8", english: "go on to do sth.", chinese: "继续做某事", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU8", english: "star in", chinese: "在...... 中担任主角", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },

  // --- 8AU8 Sentences ---
  { id: generateId(), group: "8AU8", english: "A dog will love you faithfully and is always pleased to see you.", chinese: "狗狗会忠诚地爱你并且见到你总是很高兴。", type: 'sentence', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU8", english: "They have no choice but to keep their dogs inside most of the time.", chinese: "大多数时候，他们除了把狗狗养在室内别无选择。", type: 'sentence', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU8", english: "This is not good for dogs since they need fresh air and large open spaces where they can run free.", chinese: "这样对狗狗不好，因为他们需要新鲜的空气和让它们能自由奔跑的开阔空间。", type: 'sentence', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU8", english: "An owner needs to buy food and toys for his or her dog, and if the dog gets ill, it needs to be taken to the vet.", chinese: "主人需要为他(她)的狗狗买食物和玩具，而且如果狗生病了，还需要带去看兽医。", type: 'sentence', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU8", english: "Because of all these reasons, I would advise you not to get a dog as a pet.", chinese: "由于所有这些原因，我会建议你不要养狗狗作宠物。", type: 'sentence', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
];

export const INTERVALS = [
  60 * 1000,               // Stage 0: 1 minute (Typically for 'Again')
  10 * 60 * 1000,          // Stage 1: 10 minutes
  24 * 60 * 60 * 1000,     // Stage 2: 1 day
  3 * 24 * 60 * 60 * 1000, // Stage 3: 3 days
  7 * 24 * 60 * 60 * 1000, // Stage 4: 7 days
  15 * 24 * 60 * 60 * 1000,// Stage 5: 15 days
  30 * 24 * 60 * 60 * 1000 // Stage 6: 30 days
];