import { StudyItem } from './types';

const generateId = () => Math.random().toString(36).substr(2, 9);

export const DEFAULT_STUDY_DATA: StudyItem[] = [
  // --- 8AU5 Phrases ---
  { id: generateId(), group: "8AU5", english: "at the weekend/at weekends", chinese: "在周末/在每个周末", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU5", english: "go on tours with...", chinese: "和……去游览", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU5", english: "visit places of interest", chinese: "参观名胜古迹", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU5", english: "such as /for example /for instance", chinese: "比如", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU5", english: "in person", chinese: "亲自", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU5", english: "snake its way through", chinese: "蜿蜒穿过", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU5", english: "get to do sth.", chinese: "有机会做某事", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU5", english: "so far", chinese: "到目前为止", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU5", english: "a bit of+n. / a bit+adj./adv.", chinese: "一点....../有点......", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU5", english: "introduce sb to sth.", chinese: "使某人了解某物", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU5", english: "as well", chinese: "也", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU5", english: "be different from……", chinese: "与……不同", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU5", english: "keep trying", chinese: "继续尝试", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU5", english: "plan to do sth.", chinese: "计划做某事", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU5", english: "keep in touch with sb", chinese: "与某人保持联系", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU5", english: "one another", chinese: "互相，彼此", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU5", english: "come over to", chinese: "来到", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU5", english: "can’t wait (to do sth.)", chinese: "迫不及待（做......）", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU5", english: "be grateful for……", chinese: "对……心存感激", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU5", english: "culture shock", chinese: "文化冲击", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU5", english: "feel unhappy about life", chinese: "对生活感到不满", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU5", english: "find it difficult to do sth.", chinese: "发现做某事很难", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU5", english: "deal with", chinese: "处理；应对", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU5", english: "in most situations", chinese: "在大多数情况下", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU5", english: "no longer/not...any more", chinese: "不再……", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU5", english: "feel at home", chinese: "感到舒适自在", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU5", english: "adapt to change", chinese: "适应变化", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU5", english: "depend on", chinese: "取决于", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU5", english: "see things from different points of view", chinese: "从不同的角度看待事物", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU5", english: "get along (well) with sb", chinese: "与……相处（得好）", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },

  // --- 8AU5 Sentences ---
  { id: generateId(), group: "8AU5", english: "At the weekend, they go on tours with their host families around Beijing and visit places of interest, such as the Great Wall, the Summer Palace and the National Museum.", chinese: "在周末，他们与寄宿家庭一起游览北京，参观名胜古迹，例如长城、颐和园和国家博物馆。", type: 'sentence', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU5", english: "The Great Wall is no doubt one of the most amazing achievements in human history!", chinese: "长城无疑是人类历史上最惊人的成就之一！", type: 'sentence', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU5", english: "The students also spend time learning about Chinese culture.", chinese: "学生们还花时间了解中国文化。", type: 'sentence', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU5", english: "It's been a fantastic experience so far.", chinese: "到目前为止，这是一次极好的经历。", type: 'sentence', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU5", english: "If you travel to a foreign country, you may feel confused, strange or anxious.", chinese: "如果你去国外旅行，你可能会感到困惑、陌生或焦虑。", type: 'sentence', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },

  // --- 8AU6 Phrases ---
  { id: generateId(), group: "8AU6", english: "common features", chinese: "共同特点", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU6", english: "take place", chinese: "发生", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU6", english: "at a time", chinese: "一次", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU6", english: "look down at", chinese: "向下看，俯视", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU6", english: "sail away", chinese: "扬帆远去", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU6", english: "take sth. with sb.", chinese: "某人带上......", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU6", english: "pull sth. into sp.", chinese: "把......拉到......", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU6", english: "on wheels", chinese: "带轮子的", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU6", english: "obey order", chinese: "服从命令", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU6", english: "celebrate one’s victory", chinese: "庆祝某人的胜利", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU6", english: "make jokes about...", chinese: "开......的玩笑", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU6", english: "by midnight", chinese: "到午夜时分时", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU6", english: "except for", chinese: "除了", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU6", english: "make one’s way to", chinese: "前往......", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU6", english: "take over", chinese: "占领", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU6", english: "in the end", chinese: "最后", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU6", english: "succeed in doing sth.", chinese: "成功做......", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU6", english: "be located in", chinese: "位于......", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU6", english: "be tired of", chinese: "厌烦......", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU6", english: "go on board", chinese: "上船，登机", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU6", english: "pretend to do sth.", chinese: "假装做......", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU6", english: "be jealous of", chinese: "嫉妒......", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU6", english: "on the other side of", chinese: "在......另一边", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU6", english: "under attack", chinese: "遭受攻击", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU6", english: "be full of/be filled with", chinese: "充满", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU6", english: "turn...around", chinese: "掉头", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU6", english: "be able to do sth.", chinese: "有能力做某事", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU6", english: "order sb. to do sth.", chinese: "命令某人做某事", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU6", english: "within ten days", chinese: "十天内", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU6", english: "figure out", chinese: "弄明白，解决", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },

  // --- 8AU6 Sentences ---
  { id: generateId(), group: "8AU6", english: "The Greek army has tried for ten years to capture our city.", chinese: "希腊军队十年来一直试图占领我们的城市。", type: 'sentence', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU6", english: "Outside the main gate of the city stood a huge wooden horse.", chinese: "一座巨大的木马矗立在这座城市的主城门之外(倒装句，强调木马所在位置)。", type: 'sentence', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU6", english: "In the end, they succeeded in capturing it in just one night with a clever trick.", chinese: "最终，他们用一个巧妙的计谋，仅仅一个晚上就成功拿下了这座城。", type: 'sentence', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU6", english: "Zhou Yu was jealous of Zhuge Liang and wanted him to fail.", chinese: "周瑜嫉妒诸葛亮，想让他出丑(想让他失败)。", type: 'sentence', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU6", english: "The soldiers shouted and beat their drums loudly.", chinese: "士兵们大声呼喊，用力击鼓。", type: 'sentence', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },

  // --- 8AU7 Phrases ---
  { id: generateId(), group: "8AU7", english: "play an important role in", chinese: "在……中扮演重要角色", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU7", english: "plan to do sth.", chinese: "计划做某事", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU7", english: "take notes", chinese: "做笔记", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU7", english: "in one's mind", chinese: "在某人脑海中", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU7", english: "make a point of doing sth.", chinese: "(因重要或必要)保证做", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU7", english: "in the future", chinese: "在将来", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU7", english: "make up a story", chinese: "编一个故事", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU7", english: "so that", chinese: "为了；以便", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU7", english: "as well as", chinese: "和；以及；还有", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU7", english: "live a healthy life", chinese: "过健康的生活", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU7", english: "What's more", chinese: "此外；更重要的是", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU7", english: "regular physical exercise", chinese: "规律的锻炼", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU7", english: "a healthy diet", chinese: "健康的饮食", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU7", english: "maintain a good memory", chinese: "保持良好的记忆力", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU7", english: "Last but not least", chinese: "最后但同样重要的是", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU7", english: "plenty of", chinese: "大量", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU7", english: "experience memory loss", chinese: "经历记忆力衰退", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU7", english: "no wonder", chinese: "难怪", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU7", english: "take … out of​", chinese: "把……从……中拿出来", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU7", english: "take time to relax", chinese: "花时间放松", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU7", english: "tend to do sth.", chinese: "倾向于做某事", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU7", english: "a summary of", chinese: "……的总结", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU7", english: "as a result", chinese: "结果", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU7", english: "figure out", chinese: "弄懂；弄清楚", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU7", english: "be made up of", chinese: "由……组成", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU7", english: "seem like", chinese: "似乎是", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU7", english: "even though", chinese: "尽管", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU7", english: "a record of", chinese: "……的记录", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU7", english: "natural disasters", chinese: "自然灾害", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU7", english: "It’s amazing that +句子", chinese: "令人惊奇的是……", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },

  // --- 8AU7 Sentences ---
  { id: generateId(), group: "8AU7", english: "You will be exercising your brain as well as improving your memory!", chinese: "这样既锻炼了大脑，又提升了记忆力！", type: 'sentence', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU7", english: "Unless you take time to relax, your brain will find it hard to remember things.", chinese: "除非花时间放松，否则大脑会难以记住信息。", type: 'sentence', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU7", english: "What’s more, regular physical exercise and getting enough sleep also help improve your memory.", chinese: "此外，规律的锻炼和充足的睡眠也能帮助改善记忆。", type: 'sentence', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU7", english: "Therefore, it is quite normal for people to experience memory loss as they get older.", chinese: "因此，人们随着年龄增长出现记忆力减退是正常现象。", type: 'sentence', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU7", english: "This is a good sign as it means the tree grew well and was healthy.", chinese: "这是一个好迹象，因为这表明树木生长良好且健康。", type: 'sentence', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },

  // --- 8AU8 Phrases ---
  { id: generateId(), group: "8AU8", english: "grow up", chinese: "长大；成熟", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU8", english: "have to do sth.", chinese: "不得不做......", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU8", english: "according to......", chinese: "根据......", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU8", english: "care for = look after = take care of", chinese: "照顾；照料", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU8", english: "be pleased to do sth.", chinese: "很高兴做某事", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU8", english: "in short", chinese: "总之；简言之", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU8", english: "need to do sth.", chinese: "需要做某事", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU8", english: "keep sb. awake", chinese: "使某人保持清醒", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU8", english: "a small number of+n.复数", chinese: "少数的……", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU8", english: "what’s more = in addition", chinese: "此外；除......以外", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU8", english: "have no choice but to do sth.", chinese: "别无选择，只能……", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU8", english: "most of the time", chinese: "大多数时候", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU8", english: "run free", chinese: "自由奔跑", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU8", english: "because of +n./pron.", chinese: "因为；由于......", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU8", english: "advise sb. ( not ) to do sth.", chinese: "建议某人（不要）做某事", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU8", english: "lie around", chinese: "懒散度日；游手好闲", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU8", english: "take up much space", chinese: "占用很多空间", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU8", english: "on one's own", chinese: "独自地；独立地", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU8", english: "add up", chinese: "合计", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU8", english: "on the whole", chinese: "总之；总体而言", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU8", english: "complain about......", chinese: "抱怨......", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU8", english: "the other day", chinese: "前几天", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU8", english: "in one's opinion", chinese: "在某人看来", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU8", english: "find out", chinese: "发现；查明；弄清楚", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU8", english: "bring good luck", chinese: "带来好运", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU8", english: "a symbol of", chinese: "……的象征", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU8", english: "all kinds of", chinese: "各种各样的", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU8", english: "catch the eye of sb.", chinese: "引起某人的注意", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU8", english: "go on to do sth.", chinese: "继续做某事", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU8", english: "star in", chinese: "在...... 中担任主角", type: 'phrase', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },

  // --- 8AU8 Sentences ---
  { id: generateId(), group: "8AU8", english: "A dog will love you faithfully and is always pleased to see you.", chinese: "狗狗会忠诚地爱你并且见到你总是很高兴。", type: 'sentence', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU8", english: "They have no choice but to keep their dogs inside most of the time.", chinese: "大多数时候，他们除了把狗狗养在室内别无选择。", type: 'sentence', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU8", english: "This is not good for dogs since they need fresh air and large open spaces where they can run free.", chinese: "这样对狗狗不好，因为他们需要新鲜的空气和让它们能自由奔跑的开阔空间。", type: 'sentence', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU8", english: "An owner needs to buy food and toys for his or her dog, and if the dog gets ill, it needs to be taken to the vet.", chinese: "主人需要为他(她)的狗狗买食物和玩具，而且如果狗生病了，还需要带去看兽医。", type: 'sentence', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
  { id: generateId(), group: "8AU8", english: "Because of all these reasons, I would advise you not to get a dog as a pet.", chinese: "由于所有这些原因，我会建议你不要养狗狗作宠物。", type: 'sentence', stage: 0, nextReviewDate: Date.now(), easeFactor: 2.5 },
];

export const INTERVALS = [
  0,
  5 * 60 * 1000,
  30 * 60 * 1000,
  12 * 60 * 60 * 1000,
  24 * 60 * 60 * 1000,
  2 * 24 * 60 * 60 * 1000,
  4 * 24 * 60 * 60 * 1000,
  7 * 24 * 60 * 60 * 1000,
  15 * 24 * 60 * 60 * 1000,
];