import fs from 'fs';
import path from 'path';

const packagesDir = path.join(process.cwd(), 'public', 'packages');

if (!fs.existsSync(packagesDir)) {
  console.error('public/packages/ directory not found');
  process.exit(1);
}

const dirs = fs.readdirSync(packagesDir).filter(f =>
  fs.statSync(path.join(packagesDir, f)).isDirectory()
);

const allItems: any[] = [];
for (const dir of dirs) {
  const dataPath = path.join(packagesDir, dir, 'data.json');
  if (fs.existsSync(dataPath)) {
    allItems.push(...JSON.parse(fs.readFileSync(dataPath, 'utf-8')));
  }
}

// Write as ES module — single line JSON to keep file size reasonable
const content = `// Auto-generated by prebuild script. Do not edit.\nimport { StudyItem } from "./types";\n\nexport const STATIC_PACKAGES_DATA: StudyItem[] = ${JSON.stringify(allItems)};\n`;

const outPath = path.join(process.cwd(), 'static-packages-data.ts');
fs.writeFileSync(outPath, content);
console.log(`Generated static-packages-data.ts with ${allItems.length} items (${(content.length / 1024).toFixed(1)} KB)`);
